version: 2.1

jobs:
  build-toolchain:
    docker:
      - image: cimg/base:edge
    resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          name: Restore Toolchain
          keys:
            - v4-cache-toolchain-{{ checksum "toolchain/CMakeLists.txt" }}
      - run:
          name: "Build toolchain (if toolchain not present)"
          command: "chmod u+x .circleci/build-toolchain.sh && .circleci/build-toolchain.sh"
      - save_cache:
          name: Cache Toolchain
          paths:
            - "cmake-build-release/toolchain/output"
          key: v4-cache-toolchain-{{ checksum "toolchain/CMakeLists.txt" }}

  build-hephaestOS:
    docker:
      - image: cimg/base:edge
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          name: Restore Toolchain
          keys:
            - v4-cache-toolchain-{{ checksum "toolchain/CMakeLists.txt" }}
      - run:
          name: "Download dependencies"
          command: "chmod u+x .circleci/download-dependencies.sh && .circleci/download-dependencies.sh"
      - run:
          name: "Update Cmake"
          command: "chmod u+x .circleci/update-cmake.sh && .circleci/update-cmake.sh"
      - run:
          name: "Setup and configure cmake for OS"
          command: "cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/home/circleci/project/cmake-build-release/toolchain/output/bin/i386-pc-hephaestos-gcc -DCMAKE_CXX_COMPILER=/home/circleci/project/cmake-build-release/toolchain/output/bin/i386-pc-hephaestos-g++ -B cmake-build-release -G Ninja"
      - run:
          name: "Build OS ISO"
          command: "cmake --build cmake-build-release --target HephaestOS.iso"
      - store_artifacts:
          path: /home/circleci/project/cmake-build-release/HephaestOS.iso

workflows:
  version: 2
  build-hephaestOS-workflow:
    jobs:
      - build-toolchain
      - build-hephaestOS:
          requires:
            - build-toolchain
